# предполагаю, что это начальные параметры сервера
bind_addr = ":8080"
log_level = "debug"

[store]
database_url = "host=localhost dbname=restapi_dev sslmode=disable"
# sslmode disable тк в видео у человека он не работает так что хз
